// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Aktivnost
{
    public int IdAktivnost { get; set; }

    public string OpisAktivnosti { get; set; }

    public DateTime DatumPocetka { get; set; }

    public DateTime? DatumZavrsetka { get; set; }

    public int IdVrstaAktivnosti { get; set; }

    public virtual VrstaAktivnosti IdVrstaAktivnostiNavigation { get; set; }

    public virtual ICollection<PlanProjektum> IdPlanProjekta { get; set; } = new List<PlanProjektum>();
}