// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class PlanProjektum
{
    public int IdPlanProjekta { get; set; }

    public DateTime PlaniraniPocetakZadatka { get; set; }

    public DateTime StvarniPocetakZadatka { get; set; }

    public DateTime PlaniraniZavrsetakZadatka { get; set; }

    public DateTime? StvarniZavrsetakZadatka { get; set; }

    public int IdProjekt { get; set; }

    public int IdVoditelj { get; set; }

    public virtual Projekt IdProjektNavigation { get; set; }

    public virtual VoditeljProjektum IdVoditeljNavigation { get; set; }

    public virtual ICollection<Aktivnost> IdAktivnosts { get; set; } = new List<Aktivnost>();
}