// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class PrioritetZadatka
{
    public int IdPrioritetZadatka { get; set; }

    public string RazinaPrioriteta { get; set; }

    public virtual ICollection<Zadaci> Zadacis { get; set; } = new List<Zadaci>();
}