// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class PripadnostFirmi
{
    public int IdFirma { get; set; }

    public string NazivFirma { get; set; }

    public string AdresaSjedista { get; set; }

    public virtual ICollection<Sudionik> Sudioniks { get; set; } = new List<Sudionik>();
}