// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class ProjektnaDokumentacija
{
    public int IdDokument { get; set; }

    public string NazivDokumenta { get; set; }

    public int IdVrstaDokument { get; set; }

    public string FormatDokumenta { get; set; }

    public int IdProjekt { get; set; }

    public virtual Projekt IdProjektNavigation { get; set; }

    public virtual VrstaDokumentum IdVrstaDokumentNavigation { get; set; }
}