// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Projekt
{
    public int IdProjekt { get; set; }

    public string KraticaProjekta { get; set; }

    public string NazivProjekta { get; set; }

    public DateTime DatumPocetka { get; set; }

    public DateTime? DatumZavrsetka { get; set; }

    public int IdVrstaProjekta { get; set; }

    public virtual VrstaProjektum IdVrstaProjektaNavigation { get; set; }

    public virtual ICollection<PlanProjektum> PlanProjekta { get; set; } = new List<PlanProjektum>();

    public virtual ICollection<ProjektnaDokumentacija> ProjektnaDokumentacijas { get; set; } = new List<ProjektnaDokumentacija>();

    public virtual ICollection<RacunProjektum> RacunProjekta { get; set; } = new List<RacunProjektum>();

    public virtual ICollection<Sudjeluju> Sudjelujus { get; set; } = new List<Sudjeluju>();

    public virtual ICollection<Zahtjev> IdZahtjevs { get; set; } = new List<Zahtjev>();
}