// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class RacunProjektum
{
    public string Iban { get; set; }

    public string NazivProjekta { get; set; }

    public string StanjeRacuna { get; set; }

    public int IdProjekt { get; set; }

    public virtual Projekt IdProjektNavigation { get; set; }

    public virtual ICollection<Transakcija> IdTransakcijas { get; set; } = new List<Transakcija>();
}