// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Sudionik
{
    public int IdSudionik { get; set; }

    public string Email { get; set; }

    public string Kontakt { get; set; }

    public string AdresaUreda { get; set; }

    public int IdFirma { get; set; }

    public virtual PripadnostFirmi IdFirmaNavigation { get; set; }

    public virtual ICollection<Sudjeluju> Sudjelujus { get; set; } = new List<Sudjeluju>();
}