// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Sudjeluju
{
    public int IdProjekt { get; set; }

    public int IdUloga { get; set; }

    public int IdSudionik { get; set; }

    public virtual Projekt IdProjektNavigation { get; set; }

    public virtual Sudionik IdSudionikNavigation { get; set; }

    public virtual Uloge IdUlogaNavigation { get; set; }
}