// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Transakcija
{
    public int IdTransakcija { get; set; }

    public string Ibanposiljatelja { get; set; }

    public string Ibanprimatelja { get; set; }

    public string OpisTransakcije { get; set; }

    public string Iznos { get; set; }

    public int IdVrstaTransakcije { get; set; }

    public virtual VrstaTransakcije IdVrstaTransakcijeNavigation { get; set; }

    public virtual ICollection<RacunProjektum> Ibans { get; set; } = new List<RacunProjektum>();
}