// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VoditeljProjektum
{
    public int IdVoditelj { get; set; }

    public string ImeVoditelja { get; set; }

    public string PrezimeVoditelja { get; set; }

    public int? Oib { get; set; }

    public virtual ICollection<PlanProjektum> PlanProjekta { get; set; } = new List<PlanProjektum>();
}