// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaAktivnosti
{
    public int IdVrstaAktivnosti { get; set; }

    public string NazivAktivnosti { get; set; }

    public virtual ICollection<Aktivnost> Aktivnosts { get; set; } = new List<Aktivnost>();
}