// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaDokumentum
{
    public int IdVrstaDokument { get; set; }

    public string NazivVrste { get; set; }

    public virtual ICollection<ProjektnaDokumentacija> ProjektnaDokumentacijas { get; set; } = new List<ProjektnaDokumentacija>();
}