// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Zahtjev
{
    public int IdZahtjev { get; set; }

    public string Opis { get; set; }

    public string Prioritet { get; set; }

    public string Vrsta { get; set; }

    public virtual ICollection<Zadaci> Zadacis { get; set; } = new List<Zadaci>();

    public virtual ICollection<Projekt> IdProjekts { get; set; } = new List<Projekt>();
}